services:
  - type: web
    name: flask-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade  # 在部署时自动执行数据库迁移
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:create_app()
    envVars:
      - key: DATABASE_URL
        sync: false # 让 Render 使用 Web Service 里配置的 DATABASE_URL

