services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade
      gunicorn -w 4 -b 0.0.0.0:$PORT app:create_app()
    envVars:
      - key: DATABASE_URL
        sync: false
